variable "location" {}
variable "rg_name" {}
variable "aks_name" {}
variable "vnet_name" {}
variable "vnet_cidr" {}
variable "system_subnet_cidr" {}
variable "user_subnet_cidr" {}
variable "acr_name" {}
variable "log_name" {}
variable "user_vm_size" {}
variable "admin_group_object_id" {}
